<?php

return [
    'image' => [
        'thumbnail' => [150, 150],
        'medium' => [400, 400],
        'larage' => [600, 600],
    ],
    'work_application' => [
        'status' => [
            'new' => 1,
            'apply' => 2, 
        ]
    ],
    'language_skills' => [
        1 => 'Arabic',
        2 => 'Bengali',
        3 => 'Bulgarian',
        4 => 'Burmese',
        5 => 'Cambodian',
        6 => 'Cebuano',
        7 => 'Chinese (Cantonese)',
        8 => 'Chinese (Mandarin)',
        9 => 'Czech',
        10 => 'Danish',
        11 => 'Dutch',
        12 => 'English',
        13 => 'Finnish',
        14 => 'French',
        15 => 'German',
        16 => 'Greek',
        17 => 'Hindi',
        18 => 'Hungarian',
        19 => 'Indonesian',
        20 => 'Italian',
        21 => 'Japanese',
        22 => 'Javanese',
        23 => 'Korean',
        24 => 'Laotian',
        25 => 'Malay',
        26 => 'Norwegian',
        27 => 'Polish',
        28 => 'Portuguese',
        29 => 'Romanian',
        30 => 'Russian',
        31 => 'Spanish',
        32 => 'Swedish',
        33 => 'Tagolog',
        34 => 'Taiwanese',
        35 => 'Thai',
        36 => 'Turkish',
        38 => 'Vietnamese',
        39 => 'Other',
    ],
];